[package]
name = "sentinel"
version = "0.1.0"
authors = ["Andrew Abbott <mirrexagon@mirrexagon.com>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
regex = "0.2"
markov = "1.0"
typemap = "0.3"

[dependencies.serenity]
version = "0.5"
features = ["voice"]
