[package]
name = "sentinel"
version = "0.1.0"
authors = ["Andrew Abbott <mirrexagon@mirrexagon.com>"]

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
regex = "1.1.6"
markov = "1.0.2"
typemap = "0.3.3"

[dependencies.serenity]
version = "0.5.13"
features = ["voice"]
